[package]
name = "exportmymailintomd"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
openssl = "0.10"
native-tls = "0.2"
tokio = { version = "1", features = ["full"] }
imap = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
